<?php


namespace frontend\controllers\transaction;

use common\models\transaction\Transaction;
use yii\data\ActiveDataProvider;
use yii\data\Sort;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

class MainController extends Controller
{
    public function behaviors()
    {
        return ArrayHelper::merge([
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ], parent::behaviors()); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $provider = new ActiveDataProvider([
            'query' => Transaction::find()
                ->with(['currency'])
                ->filterByPaymentAccountId(\Yii::$app->user->identity->paymentAccount->getId()),
            'sort' => new Sort([
                'defaultOrder' => [
                    'id' => SORT_DESC
                ]
            ])
        ]);

        return $this->render('index', [
            'provider' => $provider
        ]);
    }

}